import type { Business, Review, User } from "./types"

// Sample businesses data
export const businessesData: Business[] = [
  {
    id: 1,
    name: "Doner Hut",
    users: 3,
    reviews: 42,
    avgRating: 4.2,
    status: "active",
    createdAt: "May 15, 2025",
  },
  {
    id: 2,
    name: "Tech Solutions Inc",
    users: 5,
    reviews: 78,
    avgRating: 4.7,
    status: "active",
    createdAt: "May 12, 2025",
  },
  {
    id: 3,
    name: "Green Gardens",
    users: 2,
    reviews: 23,
    avgRating: 4.5,
    status: "active",
    createdAt: "May 10, 2025",
  },
  {
    id: 4,
    name: "City Fitness",
    users: 4,
    reviews: 56,
    avgRating: 4.3,
    status: "active",
    createdAt: "May 8, 2025",
  },
  {
    id: 5,
    name: "Bright Smiles Dental",
    users: 3,
    reviews: 34,
    avgRating: 4.8,
    status: "active",
    createdAt: "May 5, 2025",
  },
  {
    id: 6,
    name: "Urban Coffee",
    users: 2,
    reviews: 18,
    avgRating: 4.1,
    status: "pending",
    createdAt: "May 17, 2025",
  },
  {
    id: 7,
    name: "Fresh Grocery",
    users: 1,
    reviews: 0,
    avgRating: 0,
    status: "pending",
    createdAt: "May 16, 2025",
  },
]

// Sample users data
export const usersData: User[] = [
  {
    id: 1,
    name: "John Smith",
    email: "john@donerhut.com",
    business: "Doner Hut",
    businessId: 1,
    role: "owner",
    status: "active",
    lastLogin: "Today, 10:30 AM",
  },
  {
    id: 2,
    name: "Sarah Johnson",
    email: "sarah@techsolutions.com",
    business: "Tech Solutions Inc",
    businessId: 2,
    role: "admin",
    status: "active",
    lastLogin: "Yesterday, 3:45 PM",
  },
  {
    id: 3,
    name: "Michael Brown",
    email: "michael@greengardens.com",
    business: "Green Gardens",
    businessId: 3,
    role: "manager",
    status: "active",
    lastLogin: "May 15, 2025",
  },
  {
    id: 4,
    name: "Emily Davis",
    email: "emily@cityfitness.com",
    business: "City Fitness",
    businessId: 4,
    role: "owner",
    status: "active",
    lastLogin: "May 14, 2025",
  },
  {
    id: 5,
    name: "Robert Wilson",
    email: "robert@brightsmiles.com",
    business: "Bright Smiles Dental",
    businessId: 5,
    role: "admin",
    status: "active",
    lastLogin: "May 12, 2025",
  },
  {
    id: 6,
    name: "Jennifer Lee",
    email: "jennifer@urbancoffee.com",
    business: "Urban Coffee",
    businessId: 6,
    role: "owner",
    status: "pending",
    lastLogin: "Never",
  },
  {
    id: 7,
    name: "David Miller",
    email: "david@freshgrocery.com",
    business: "Fresh Grocery",
    businessId: 7,
    role: "owner",
    status: "pending",
    lastLogin: "Never",
  },
]

// Sample reviews data
export const reviewsData: Review[] = [
  {
    id: 1,
    name: "Vishnu Vardhan S",
    rating: 1,
    date: "May 14, 2025",
    message: "Bad Taste",
    location: "Doner Hut",
    email: "vishnu@example.com",
    phone: "+91 98765 43210",
    replied: false,
    approved: true,
  },
  {
    id: 2,
    name: "Aravind",
    rating: 5,
    date: "May 8, 2025",
    message:
      "Amazing food! The flavors were incredible and the service was top-notch. Will definitely be coming back soon.",
    location: "Doner Hut",
    replied: true,
    approved: true,
  },
  {
    id: 3,
    name: "Chandran K",
    rating: 5,
    date: "Mar 20, 2025",
    message: "Loved it! Great atmosphere and friendly staff.",
    location: "Doner Hut",
    replied: false,
    approved: true,
  },
  {
    id: 4,
    name: "John D.",
    rating: 4,
    date: "Mar 15, 2025",
    message: "Great service, will come back! The food was delicious and reasonably priced.",
    location: "Doner Hut",
    replied: true,
    approved: true,
  },
  {
    id: 5,
    name: "Sarah M.",
    rating: 3,
    date: "Mar 10, 2025",
    message: "Food was okay, service could be better. Waited too long for my order.",
    location: "Doner Hut",
    email: "sarah@example.com",
    phone: "+91 87654 32109",
    replied: false,
    approved: true,
  },
  {
    id: 6,
    name: "Michael P.",
    rating: 2,
    date: "Mar 5, 2025",
    message: "Disappointing experience. Food was cold when it arrived.",
    location: "Doner Hut",
    email: "michael@example.com",
    phone: "+91 76543 21098",
    replied: false,
    approved: false,
  },
]
